nginx:
    container_name: wm_nginx
    build: ./docker/nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - phpfpm:nginx
        - mysql:nginx
    volumes:
        - ./magento:/var/www/html
    hostname: docker.webmeridian.local

phpfpm:
    container_name: wm_phpfpm7
    build: ./docker/php-fpm
    ports:
        - "9001:9001"
    links:
        - mysql:phpfpm
    volumes:
        - ./magento:/var/www/html
    environment:
        - PHP_IDE_CONFIG="serverName=Docker"

mysql:
    container_name: wm_mysql
    image: mysql:5.6
    ports:
        - "3306:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_PASSWORD=1234
        - MYSQL_DATABASE=webmeridian
        - MYSQL_USER=admin
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8090:80
    links:
        - mysql:db